# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0004_auto_20160306_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='provider_name',
            new_name='backend',
        ),
        migrations.RenameField(
            model_name='paascredential',
            old_name='provider_name',
            new_name='backend',
        ),
        migrations.AlterUniqueTogether(
            name='paascredential',
            unique_together=set([('profile', 'backend')]),
        ),
    ]
