# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 22:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0002_auto_20160229_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(regex='[a-z0-9-]+')])),
                ('provider_name', models.CharField(max_length=50)),
            ],
        ),
    ]
