# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 19:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0003_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_id',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(regex='^[a-z0-9-]+$')]),
        ),
    ]
