# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 13:12
from __future__ import unicode_literals

import api_server.addons.state
import api_server.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0005_auto_20160306_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_uuid', models.UUIDField()),
                ('state', api_server.fields.EnumField(enum_class=api_server.addons.state.AddonState)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_server.App')),
            ],
        ),
    ]
