# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 14:31
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0006_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='config',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
