# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 22:25
from __future__ import unicode_literals

import api_server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0008_auto_20160308_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='display_name',
            field=models.CharField(default=api_server.models._make_display_name, max_length=100, unique=True),
        ),
    ]
