# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 18:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0010_addon_config_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='config_customization',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[A-Z0-9_]+$')]),
        ),
    ]
