# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import docker_addons.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=docker_addons.models.make_container_name, max_length=50, unique=True)),
            ],
        ),
    ]
