# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docker_addons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Container',
            new_name='ContainerInfo',
        ),
    ]
