# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_addons', '0002_auto_20160327_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerinfo',
            name='container_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
