# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import docker_addons.models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_addons', '0003_containerinfo_container_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerinfo',
            name='name',
            field=models.CharField(default=docker_addons.models.make_container_name, editable=False, max_length=50, unique=True),
        ),
    ]
