# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 14:35
from __future__ import unicode_literals

import aws_db_addons.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbInstance',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aws_instance_identifier', models.CharField(default=aws_db_addons.models.make_instance_identifier, editable=False, max_length=63, unique=True)),
                ('db_name', models.CharField(default=aws_db_addons.models.make_db_name, editable=False, max_length=64)),
                ('master_username', models.CharField(default=aws_db_addons.models.make_username, editable=False, max_length=16)),
                ('master_password', models.CharField(default=aws_db_addons.models.make_password, editable=False, max_length=30)),
            ],
        ),
    ]
